# Generated by Django 5.2.12 on 2026-03-12 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم التصنيف"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "تصنيف مؤشر",
                "verbose_name_plural": "تصنيفات المؤشرات",
                "db_table": "indicator_categories",
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="اسم المؤشر")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="الوصف"),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("number", "رقم"),
                            ("percentage", "نسبة مئوية"),
                            ("text", "نص"),
                            ("hours", "ساعات"),
                            ("days", "أيام"),
                        ],
                        max_length=20,
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "unit_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="تسمية الوحدة",
                    ),
                ),
                (
                    "accumulation_type",
                    models.CharField(
                        choices=[
                            ("sum", "مجموع"),
                            ("average", "متوسط"),
                            ("last_value", "آخر قيمة"),
                        ],
                        max_length=20,
                        verbose_name="طريقة التجميع",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_indicators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicators",
                        to="indicators.indicatorcategory",
                        verbose_name="التصنيف",
                    ),
                ),
            ],
            options={
                "verbose_name": "مؤشر",
                "verbose_name_plural": "المؤشرات",
                "db_table": "indicators",
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="idx_indicator_cat_active",
                    ),
                    models.Index(fields=["unit_type"], name="idx_indicator_unit_type"),
                ],
            },
        ),
    ]
