# Generated by Django 5.2.12 on 2026-03-12 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("period_opened", "فتح أسبوع جديد"),
                            ("submission_due", "اقتراب الموعد النهائي"),
                            ("submission_late", "تأخر في التسليم"),
                            ("extension_granted", "منح تمديد"),
                            ("form_pending_approval", "استمارة بانتظار الاعتماد"),
                            ("form_approved", "اعتماد الاستمارة"),
                            ("form_rejected", "رفض الاستمارة"),
                            ("submission_received", "استلام منجز"),
                            ("submission_approved", "اعتماد المنجز"),
                            ("qualitative_pending", "منجز نوعي بانتظار الاعتماد"),
                            ("qualitative_approved", "اعتماد المنجز النوعي"),
                            ("qualitative_rejected", "رفض المنجز النوعي"),
                        ],
                        max_length=30,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "related_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="النموذج المرتبط",
                    ),
                ),
                (
                    "related_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرف المرتبط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_583549_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="idx_notification_created"
                    ),
                    models.Index(
                        fields=["notification_type"], name="idx_notification_type"
                    ),
                ],
            },
        ),
    ]
