# Generated by Django 5.2.12 on 2026-03-12 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("indicators", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="السنة")),
                ("target_value", models.FloatField(verbose_name="القيمة المستهدفة")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="indicators.indicator",
                        verbose_name="المؤشر",
                    ),
                ),
                (
                    "qism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="organization.organizationunit",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="set_targets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدد بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستهدف",
                "verbose_name_plural": "المستهدفات",
                "db_table": "targets",
                "indexes": [
                    models.Index(
                        fields=["qism", "indicator", "year"],
                        name="idx_target_qism_ind_year",
                    ),
                    models.Index(fields=["year"], name="idx_target_year"),
                ],
                "unique_together": {("qism", "indicator", "year")},
            },
        ),
    ]
