# Generated by Django 6.0.3 on 2026-04-15 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submission_created', 'إنشاء منجز'), ('submission_saved', 'حفظ إجابات منجز'), ('submission_submitted', 'إرسال منجز للاعتماد'), ('submission_planning_approved', 'اعتماد منجز من التخطيط'), ('submission_planning_returned', 'إرجاع منجز من التخطيط'), ('submission_admin_approved', 'اعتماد منجز من الإحصاء'), ('submission_admin_edited', 'تعديل منجز من الإحصاء'), ('submission_admin_returned', 'إرجاع منجز من الإحصاء للتخطيط'), ('qualitative_planning_approved', 'اعتماد نوعي من التخطيط'), ('qualitative_planning_rejected', 'رفض نوعي من التخطيط'), ('qualitative_admin_approved', 'اعتماد نوعي من الإحصاء'), ('qualitative_admin_rejected', 'رفض نوعي من الإحصاء'), ('template_created', 'إنشاء قالب استمارة'), ('template_updated', 'تعديل قالب استمارة'), ('template_submitted', 'تقديم قالب للاعتماد'), ('template_approved', 'اعتماد قالب'), ('template_rejected', 'رفض قالب'), ('template_new_version', 'إنشاء إصدار جديد'), ('target_created', 'إنشاء مستهدف'), ('target_updated', 'تعديل مستهدف'), ('target_deleted', 'حذف مستهدف'), ('extension_granted', 'منح تمديد موعد'), ('period_opened', 'فتح أسبوع'), ('period_closed', 'إغلاق أسبوع')], max_length=50, verbose_name='نوع الإجراء')),
                ('actor_role', models.CharField(blank=True, default='', help_text='يُحفَظ للاحتفاظ بالسياق حتى عند تغيير دور المستخدم لاحقاً', max_length=30, verbose_name='دور المنفِّذ')),
                ('target_model', models.CharField(help_text='اسم النموذج المستهدَف مثل WeeklySubmission, FormTemplate', max_length=50, verbose_name='نموذج الكائن')),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='معرّف الكائن')),
                ('target_repr', models.CharField(blank=True, default='', help_text='وصف نصّي للكائن وقت الإجراء (لا يتأثّر بتغييرات لاحقة)', max_length=255, verbose_name='وصف الكائن')),
                ('field_changes', models.JSONField(blank=True, default=None, null=True, verbose_name='تفاصيل التعديلات')),
                ('reason', models.TextField(blank=True, default='', verbose_name='السبب')),
                ('metadata', models.JSONField(blank=True, default=None, null=True, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجراء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='المنفِّذ')),
                ('qism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.organizationunit', verbose_name='القسم المرتبط')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='idx_audit_target'), models.Index(fields=['action_type'], name='idx_audit_action'), models.Index(fields=['actor'], name='idx_audit_actor'), models.Index(fields=['qism', '-created_at'], name='idx_audit_qism_time'), models.Index(fields=['-created_at'], name='idx_audit_time')],
            },
        ),
    ]
