# Generated by Django 5.2.14 on 2026-05-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("submission_created", "إنشاء منجز"),
                    ("submission_saved", "حفظ إجابات منجز"),
                    ("submission_submitted", "إرسال منجز للاعتماد"),
                    ("submission_planning_approved", "اعتماد منجز من التخطيط"),
                    ("submission_planning_returned", "إرجاع منجز من التخطيط"),
                    ("submission_admin_approved", "اعتماد منجز من الإحصاء"),
                    ("submission_admin_edited", "تعديل منجز من الإحصاء"),
                    ("submission_admin_returned", "إرجاع منجز من الإحصاء للتخطيط"),
                    ("qualitative_planning_approved", "اعتماد نوعي من التخطيط"),
                    ("qualitative_planning_rejected", "رفض نوعي من التخطيط"),
                    ("qualitative_admin_approved", "اعتماد نوعي من الإحصاء"),
                    ("qualitative_admin_rejected", "رفض نوعي من الإحصاء"),
                    ("template_created", "إنشاء قالب استمارة"),
                    ("template_updated", "تعديل قالب استمارة"),
                    ("template_submitted", "تقديم قالب للاعتماد"),
                    ("template_approved", "اعتماد قالب"),
                    ("template_rejected", "رفض قالب"),
                    ("template_new_version", "إنشاء إصدار جديد"),
                    ("target_created", "إنشاء مستهدف"),
                    ("target_updated", "تعديل مستهدف"),
                    ("target_deleted", "حذف مستهدف"),
                    ("extension_granted", "منح تمديد موعد"),
                    ("period_opened", "فتح أسبوع"),
                    ("period_closed", "إغلاق أسبوع"),
                    ("user_created", "إنشاء مستخدم"),
                    ("user_updated", "تعديل بيانات مستخدم"),
                    ("user_password_reset", "إعادة تعيين كلمة المرور"),
                    ("user_deactivated", "تعطيل مستخدم"),
                    ("user_reactivated", "تفعيل مستخدم"),
                    ("indicator_created", "إنشاء مؤشّر"),
                    ("indicator_updated", "تعديل مؤشّر"),
                    ("indicator_deactivated", "تعطيل مؤشّر"),
                ],
                max_length=50,
                verbose_name="نوع الإجراء",
            ),
        ),
    ]
