# Generated by Django 5.2.12 on 2026-03-12 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("indicators", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="رقم الإصدار")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending_approval", "بانتظار الاعتماد"),
                            ("approved", "معتمد"),
                            ("superseded", "مُستبدَل"),
                            ("rejected", "مرفوض"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "effective_from_week",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="يسري من الأسبوع"
                    ),
                ),
                (
                    "effective_from_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="يسري من السنة"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, default="", verbose_name="سبب الرفض"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمد بواسطة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "qism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_templates",
                        to="organization.organizationunit",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رفض بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب استمارة",
                "verbose_name_plural": "قوالب الاستمارات",
                "db_table": "form_templates",
            },
        ),
        migrations.CreateModel(
            name="FormTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="إلزامي"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "form_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="forms.formtemplate",
                        verbose_name="القالب",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_items",
                        to="indicators.indicator",
                        verbose_name="المؤشر",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند استمارة",
                "verbose_name_plural": "بنود الاستمارة",
                "db_table": "form_template_items",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(fields=["qism", "status"], name="idx_form_qism_status"),
        ),
        migrations.AddIndex(
            model_name="formtemplate",
            index=models.Index(fields=["status"], name="idx_form_status"),
        ),
        migrations.AlterUniqueTogether(
            name="formtemplate",
            unique_together={("qism", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="formtemplateitem",
            unique_together={("form_template", "indicator")},
        ),
    ]
