# Generated by Django 6.0.3 on 2026-04-15 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='formtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('qism', 'effective_from_year', 'effective_from_week'), name='uniq_approved_effective_per_qism'),
        ),
    ]
