# Generated by Django 5.2.13 on 2026-05-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('statistics_admin', 'مدير قسم الإحصاء'), ('planning_section', 'قسم التخطيط'), ('section_manager', 'مدير قسم'), ('viewer', 'مُطّلِع')], max_length=30, verbose_name='الدور'),
        ),
    ]
