# Generated by Django 5.2.12 on 2026-03-12 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="السنة")),
                (
                    "week_number",
                    models.PositiveIntegerField(verbose_name="رقم الأسبوع"),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                ("deadline", models.DateTimeField(verbose_name="الموعد النهائي")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "مفتوح"), ("closed", "مغلق")],
                        default="open",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فترة أسبوعية",
                "verbose_name_plural": "الفترات الأسبوعية",
                "db_table": "weekly_periods",
                "ordering": ["-year", "-week_number"],
            },
        ),
        migrations.CreateModel(
            name="QismExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_deadline", models.DateTimeField(verbose_name="الموعد الجديد")),
                ("reason", models.TextField(verbose_name="السبب")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_extensions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منح بواسطة",
                    ),
                ),
                (
                    "qism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="organization.organizationunit",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "weekly_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="submissions.weeklyperiod",
                        verbose_name="الفترة الأسبوعية",
                    ),
                ),
            ],
            options={
                "verbose_name": "تمديد موعد",
                "verbose_name_plural": "تمديدات المواعيد",
                "db_table": "qism_extensions",
            },
        ),
        migrations.CreateModel(
            name="WeeklySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("submitted", "مُرسل"),
                            ("approved", "معتمد"),
                            ("late", "متأخر"),
                            ("extended", "مُمدَّد"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإرسال"
                    ),
                ),
                (
                    "planning_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                (
                    "form_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms.formtemplate",
                        verbose_name="قالب الاستمارة",
                    ),
                ),
                (
                    "planning_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمد بواسطة (التخطيط)",
                    ),
                ),
                (
                    "qism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="organization.organizationunit",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "weekly_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="submissions.weeklyperiod",
                        verbose_name="الفترة الأسبوعية",
                    ),
                ),
            ],
            options={
                "verbose_name": "منجز أسبوعي",
                "verbose_name_plural": "المنجزات الأسبوعية",
                "db_table": "weekly_submissions",
            },
        ),
        migrations.CreateModel(
            name="SubmissionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numeric_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="القيمة الرقمية"
                    ),
                ),
                (
                    "text_value",
                    models.TextField(
                        blank=True, default="", verbose_name="القيمة النصية"
                    ),
                ),
                (
                    "is_qualitative",
                    models.BooleanField(default=False, verbose_name="منجز نوعي"),
                ),
                (
                    "qualitative_details",
                    models.TextField(
                        blank=True, default="", verbose_name="تفاصيل المنجز النوعي"
                    ),
                ),
                (
                    "qualitative_status",
                    models.CharField(
                        choices=[
                            ("none", "لا يوجد"),
                            ("pending_planning", "بانتظار اعتماد التخطيط"),
                            ("pending_statistics", "بانتظار اعتماد الإحصاء"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="none",
                        max_length=25,
                        verbose_name="حالة المنجز النوعي",
                    ),
                ),
                (
                    "qualitative_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ اعتماد النوعي"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, default="", verbose_name="سبب الرفض"),
                ),
                (
                    "form_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="forms.formtemplateitem",
                        verbose_name="بند الاستمارة",
                    ),
                ),
                (
                    "qualitative_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_qualitatives",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمد نوعياً بواسطة",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="submissions.weeklysubmission",
                        verbose_name="المنجز",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجابة منجز",
                "verbose_name_plural": "إجابات المنجزات",
                "db_table": "submission_answers",
            },
        ),
        migrations.AddIndex(
            model_name="weeklyperiod",
            index=models.Index(
                fields=["year", "week_number"], name="idx_period_year_week"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyperiod",
            index=models.Index(fields=["status"], name="idx_period_status"),
        ),
        migrations.AlterUniqueTogether(
            name="weeklyperiod",
            unique_together={("year", "week_number")},
        ),
        migrations.AlterUniqueTogether(
            name="qismextension",
            unique_together={("qism", "weekly_period")},
        ),
        migrations.AddIndex(
            model_name="weeklysubmission",
            index=models.Index(
                fields=["qism", "weekly_period"], name="idx_sub_qism_period"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklysubmission",
            index=models.Index(
                fields=["weekly_period", "status"], name="idx_sub_period_status"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklysubmission",
            index=models.Index(fields=["status"], name="idx_sub_status"),
        ),
        migrations.AlterUniqueTogether(
            name="weeklysubmission",
            unique_together={("qism", "weekly_period")},
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["submission", "form_item"], name="idx_answer_sub_item"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissionanswer",
            unique_together={("submission", "form_item")},
        ),
    ]
