# Generated by Django 6.0.3 on 2026-04-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_returned_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_day', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], default=5, help_text='اليوم الذي يبدأ به الأسبوع رسمياً (يوم السبت هو الافتراضي)', verbose_name='يوم بداية الأسبوع')),
                ('deadline_days_after_week_end', models.PositiveIntegerField(default=3, help_text='عدد الأيام بعد نهاية الأسبوع حتى الموعد النهائي للتسليم', verbose_name='أيام الموعد النهائي بعد نهاية الأسبوع')),
                ('deadline_hour', models.PositiveIntegerField(default=12, help_text='الساعة من اليوم (0-23) للموعد النهائي. الافتراضي 12 ظهراً', verbose_name='ساعة الموعد النهائي')),
                ('auto_create_enabled', models.BooleanField(default=True, help_text='عند التفعيل، يُنشئ النظام الأسبوع الحالي تلقائياً في بدايته', verbose_name='تفعيل الإنشاء التلقائي للأسابيع')),
                ('auto_close_previous', models.BooleanField(default=True, help_text='يُغلق الأسبوع السابق تلقائياً بعد مرور الموعد النهائي', verbose_name='إغلاق الأسبوع السابق تلقائياً بعد انتهاء موعده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'db_table': 'system_configuration',
            },
        ),
    ]
