# Generated by Django 6.0.3 on 2026-04-15 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_systemconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysubmission',
            name='admin_review_action',
            field=models.CharField(blank=True, default='', help_text='approved / edited / returned', max_length=20, verbose_name='إجراء مراجعة الإحصاء'),
        ),
        migrations.AddField(
            model_name='weeklysubmission',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ مراجعة الإحصاء'),
        ),
        migrations.AddField(
            model_name='weeklysubmission',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='مراجَع بواسطة (الإحصاء)'),
        ),
        migrations.AlterField(
            model_name='weeklysubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُرسل'), ('approved', 'معتمد'), ('returned', 'مُرجَع للتصحيح'), ('late', 'متأخر'), ('extended', 'مُمدَّد'), ('returned_by_admin', 'مُرجَع من الإحصاء')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
