# Generated by Django 5.2.12 on 2026-03-12 01:26

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الكيان")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="الرمز"),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("daira", "دائرة"),
                            ("mudiriya", "مديرية"),
                            ("qism", "قسم"),
                        ],
                        max_length=20,
                        verbose_name="نوع الكيان",
                    ),
                ),
                (
                    "qism_role",
                    models.CharField(
                        choices=[
                            ("regular", "عادي"),
                            ("planning", "تخطيط"),
                            ("statistics", "إحصاء"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="دور القسم",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organization.organizationunit",
                        verbose_name="الكيان الأب",
                    ),
                ),
            ],
            options={
                "verbose_name": "كيان تنظيمي",
                "verbose_name_plural": "الكيانات التنظيمية",
                "db_table": "organization_units",
                "indexes": [
                    models.Index(fields=["unit_type"], name="idx_org_units_type"),
                    models.Index(fields=["parent"], name="idx_org_units_parent"),
                    models.Index(
                        fields=["tree_id", "lft", "rght"], name="idx_org_units_mptt"
                    ),
                    models.Index(
                        fields=["tree_id", "lft"], name="organization_organizationue07f"
                    ),
                ],
            },
        ),
    ]
