# Generated by Django 5.2.13 on 2026-05-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationunit',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='معرّف الوحدة في نظام الهيكل التنظيمي المركزي', null=True, unique=True, verbose_name='المعرّف الخارجي'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='external_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة مع النظام الخارجي'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرمز'),
        ),
    ]
