# Generated by Django 5.2.13 on 2026-05-15 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationunit_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('context_parent', models.ForeignKey(blank=True, help_text='للعرض في التقارير فقط — لا يقيّد نطاق الإشراف', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.organizationunit', verbose_name='المديرية/الدائرة الأم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planning_assignments', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('planning_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='planning_assignment', to='organization.organizationunit', verbose_name='الوحدة العاملة كقسم تخطيط')),
            ],
            options={
                'verbose_name': 'تخصيص قسم تخطيط',
                'verbose_name_plural': 'تخصيصات أقسام التخطيط',
                'db_table': 'planning_assignments',
            },
        ),
        migrations.CreateModel(
            name='ViewScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_view_scopes', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view_scope', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('viewable_units', models.ManyToManyField(blank=True, related_name='view_scope_users', to='organization.organizationunit', verbose_name='الوحدات القابلة للاطّلاع')),
            ],
            options={
                'verbose_name': 'نطاق اطّلاع',
                'verbose_name_plural': 'نطاقات الاطّلاع',
                'db_table': 'view_scopes',
            },
        ),
        migrations.CreateModel(
            name='SupervisedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_units', to='organization.planningassignment', verbose_name='تخصيص قسم التخطيط')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_link', to='organization.organizationunit', verbose_name='الوحدة المُشرَف عليها')),
            ],
            options={
                'verbose_name': 'وحدة مُشرَف عليها',
                'verbose_name_plural': 'الوحدات المُشرَف عليها',
                'db_table': 'supervised_units',
                'indexes': [models.Index(fields=['assignment'], name='idx_supervised_assignment')],
            },
        ),
    ]
