# Generated by Django 5.2.13 on 2026-05-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_migrate_qism_role_to_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationunit',
            name='qism_role',
        ),
    ]
