# Generated by Django 5.2.14 on 2026-05-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_drop_qism_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUnitTypeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_type_name",
                    models.CharField(
                        db_index=True,
                        help_text="كما يُرجعه `unit_type_name` من /reference/unit-types/",
                        max_length=100,
                        unique=True,
                        verbose_name="اسم نوع الوحدة في النظام الخارجي",
                    ),
                ),
                (
                    "external_type_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اختياري — للتتبّع فقط، لا يُستخدم في الربط",
                        null=True,
                        verbose_name="المعرّف في النظام الخارجي",
                    ),
                ),
                (
                    "treat_as",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daira", "دائرة"),
                            ("mudiriya", "مديرية"),
                            ("qism", "قسم"),
                            ("ignore", "تجاهل"),
                        ],
                        help_text="اتركه فارغاً مؤقتاً حتى يُقرّر الأدمن. القيم: daira / mudiriya / qism / ignore",
                        max_length=20,
                        null=True,
                        verbose_name="يُعامَل كـ",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تطابق نوع وحدة خارجي",
                "verbose_name_plural": "تطابقات أنواع الوحدات الخارجيّة",
                "db_table": "external_unit_type_mappings",
                "ordering": ["external_type_name"],
            },
        ),
    ]
