# Generated by Django 5.2.14 on 2026-05-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_externalunittypemapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationunit",
            name="employees_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="يأتي من النظام الخارجي ويُحدَّث مع كل مزامنة.",
                verbose_name="عدد الموظّفين",
            ),
        ),
    ]
